; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps = 
	etherkit/Etherkit Si5351@^2.2.0
	etherkit/Etherkit JTEncode@^1.3.1
	paulstoffregen/Time@^1.6.1
	sensorsiot/NTPtimeESP@^1.0.0
	tzapu/WiFiManager@^2.0.17
	
